### ISSUE TITLE
【大佬  如果点击第一下 为空 体验更好】

### ISSUE THREAD

**Issue by GrammyLi** [EnixCoda/MineSweeper#2]
效果： [https://grammyli.com/g/sweeping/](https://grammyli.com/g/sweeping/)

**Comment by EnixCoda** [comment]
你好，第一下已经被设计为一定是空的

https://github.com/EnixCoda/MineSweeper/blob/04433135b76dd2f62bea89a62c83f61593526ff9/src/models/Game.tsx#L50-L54

**Comment by GrammyLi** [comment]
nb
